export const PATTERNS = [
	{key: 601, uri:require("../assets/patterns/601.png"), name: "Gravilla 1"},
	//{key: 602, uri:require("../assets/patterns/602.png"), name: "Gravilla 2"},
	{key: 603, uri:require("../assets/patterns/603.png"), name: "Gravilla cruzada"},
	{key: 605, uri:require("../assets/patterns/605.png"), name: "Brecha 1"},
	//{key: 606, uri:require("../assets/patterns/606.png"), name: "Brecha 2"},
	{key: 607, uri:require("../assets/patterns/607.png"), name: "Arenisca"},
	{key: 608, uri:require("../assets/patterns/608.png"), name: "Arenisca de capa"},
	{key: 609, uri:require("../assets/patterns/609.png"), name: "Arenisca cruzada 1"},
	//{key: 610, uri:require("../assets/patterns/610.png"), name: "Arenisca cruzada 2"},
	{key: 611, uri:require("../assets/patterns/611.png"), name: "Arenisca ondulada"},
	{key: 612, uri:require("../assets/patterns/612.png"), name: "Arenisca arcillosa"},
	{key: 613, uri:require("../assets/patterns/613.png"), name: "Arenisca calcárea"},
	{key: 614, uri:require("../assets/patterns/614.png"), name: "Arenisca dolomítica"},
	{key: 616, uri:require("../assets/patterns/616.png"), name: "Limo"},
	{key: 617, uri:require("../assets/patterns/617.png"), name: "Limo calcáreo"},
	{key: 618, uri:require("../assets/patterns/618.png"), name: "Limo dolomítico"},
	{key: 619, uri:require("../assets/patterns/619.png"), name: "Lutita arenosa"},
	{key: 620, uri:require("../assets/patterns/620.png"), name: "Arcilla"},
	{key: 621, uri:require("../assets/patterns/621.png"), name: "Lutita pizarrosa"},
	{key: 622, uri:require("../assets/patterns/622.png"), name: "Lutita dolomítica"},
	{key: 623, uri:require("../assets/patterns/623.png"), name: "Lutita calcárea"},
	{key: 624, uri:require("../assets/patterns/624.png"), name: "Lutita carbonosa"},
	{key: 625, uri:require("../assets/patterns/625.png"), name: "Lutita aceitosa"},
	{key: 626, uri:require("../assets/patterns/626.png"), name: "Tiza"},
	{key: 627, uri:require("../assets/patterns/627.png"), name: "Caliza"},
	{key: 628, uri:require("../assets/patterns/628.png"), name: "Caliza clástica"},
	{key: 629, uri:require("../assets/patterns/629.png"), name: "Caliza fosilífera clástica"},
	{key: 630, uri:require("../assets/patterns/630.png"), name: "Caliza nodular o de capa"},
	{key: 631, uri:require("../assets/patterns/631.png"), name: "Caliza irregular"},
	{key: 632, uri:require("../assets/patterns/632.png"), name: "Caliza cruzada"},
	{key: 633, uri:require("../assets/patterns/633.png"), name: "Caliza cruzada pizarrosa"},
	{key: 634, uri:require("../assets/patterns/634.png"), name: "Caliza cruzada arenosa y clástica"},
	{key: 635, uri:require("../assets/patterns/635.png"), name: "Caliza oolítica"},
	{key: 636, uri:require("../assets/patterns/636.png"), name: "Caliza arenosa"},
	{key: 637, uri:require("../assets/patterns/637.png"), name: "Caliza limosa"},
	{key: 638, uri:require("../assets/patterns/638.png"), name: "Caliza arcillosa"},
	{key: 639, uri:require("../assets/patterns/639.png"), name: "Caliza pizarrosa 1"},
	{key: 640, uri:require("../assets/patterns/640.png"), name: "Caliza pizarrosa 2"},
	{key: 641, uri:require("../assets/patterns/641.png"), name: "Caliza dolomítica"},
	{key: 642, uri:require("../assets/patterns/642.png"), name: "Dolomita"},
	{key: 643, uri:require("../assets/patterns/643.png"), name: "Dolomita cruzada"},
	{key: 644, uri:require("../assets/patterns/644.png"), name: "Dolomita oolítica"},
	{key: 645, uri:require("../assets/patterns/645.png"), name: "Dolomita arenosa"},
	{key: 646, uri:require("../assets/patterns/646.png"), name: "Dolomita limosa"},
	{key: 647, uri:require("../assets/patterns/647.png"), name: "Dolomita arcillosa"},
	{key: 648, uri:require("../assets/patterns/648.png"), name: "Dolomita pizarrosa"},
	{key: 649, uri:require("../assets/patterns/649.png"), name: "Pizarra de capa 1"},
	//{key: 650, uri:require("../assets/patterns/650.png"), name: "Pizarra de capa 2"},
	{key: 651, uri:require("../assets/patterns/651.png"), name: "Pizarra de capa fosilífera"},
	{key: 652, uri:require("../assets/patterns/652.png"), name: "Roca fosilífera"},
	{key: 653, uri:require("../assets/patterns/653.png"), name: "Roca diatomácea"},
	{key: 654, uri:require("../assets/patterns/654.png"), name: "Subgrauvaca"},
	{key: 655, uri:require("../assets/patterns/655.png"), name: "Subgrauvaca cruzada"},
	{key: 656, uri:require("../assets/patterns/656.png"), name: "Subgrauvaca ondulada"},
	{key: 657, uri:require("../assets/patterns/657.png"), name: "Turba"},
	{key: 658, uri:require("../assets/patterns/658.png"), name: "Carbón"},
	{key: 659, uri:require("../assets/patterns/659.png"), name: "Carbón impuro"},
	{key: 660, uri:require("../assets/patterns/660.png"), name: "Subarcilla"},
	{key: 661, uri:require("../assets/patterns/661.png"), name: "Arcilla pedernal"},
	{key: 662, uri:require("../assets/patterns/662.png"), name: "Betonita"},
	{key: 663, uri:require("../assets/patterns/663.png"), name: "Glauconita"},
	{key: 664, uri:require("../assets/patterns/664.png"), name: "Limonita"},
	{key: 665, uri:require("../assets/patterns/665.png"), name: "Skeyerita"},
	{key: 666, uri:require("../assets/patterns/666.png"), name: "Roca fosfática nodular"},
	{key: 667, uri:require("../assets/patterns/667.png"), name: "Gypsum"},
	{key: 668, uri:require("../assets/patterns/668.png"), name: "Sal"},
	{key: 669, uri:require("../assets/patterns/669.png"), name: "Arenisca y limo en capas"},
	{key: 670, uri:require("../assets/patterns/670.png"), name: "Arenisca y lutita en capas"},
	{key: 671, uri:require("../assets/patterns/671.png"), name: "Arenisca y lutita en capas onduladas"},
	{key: 672, uri:require("../assets/patterns/672.png"), name: "Lutita (dominante) y caliza limosa en capas"},
	//{key: 673, uri:require("../assets/patterns/673.png"), name: "Lutita (dominante) y caliza en capas 1"},
	{key: 674, uri:require("../assets/patterns/674.png"), name: "Lutita (dominante) y caliza en capas 2"},
	{key: 675, uri:require("../assets/patterns/675.png"), name: "Lutita calcárea (dominante) y caliza en capas"},
	{key: 676, uri:require("../assets/patterns/676.png"), name: "Caliza limosa y caliza en capas"},
	{key: 677, uri:require("../assets/patterns/677.png"), name: "Caliza y lutita en capas 1"},
	{key: 678, uri:require("../assets/patterns/678.png"), name: "Caliza y lutita en capas 2"},
	{key: 679, uri:require("../assets/patterns/679.png"), name: "Caliza (dominante) y lutita en capas"},
	{key: 680, uri:require("../assets/patterns/680.png"), name: "Caliza y lutita calcárea en capas"},
	{key: 681, uri:require("../assets/patterns/681.png"), name: "Diamicton 1"},
	//{key: 682, uri:require("../assets/patterns/682.png"), name: "Diamicton 2"},
	//{key: 683, uri:require("../assets/patterns/683.png"), name: "Diamicton 3"},
	{key: 684, uri:require("../assets/patterns/684.png"), name: "Loess 1"},
	//{key: 685, uri:require("../assets/patterns/685.png"), name: "Loess 2"},
	//{key: 686, uri:require("../assets/patterns/686.png"), name: "Loess 3"},
	{key: 701, uri:require("../assets/patterns/701.png"), name: "Metamorfismo"},
	{key: 702, uri:require("../assets/patterns/702.png"), name: "Cuarcita"},
	{key: 703, uri:require("../assets/patterns/703.png"), name: "Pizarra"},
	{key: 704, uri:require("../assets/patterns/704.png"), name: "Granito esquistoso"},
	{key: 705, uri:require("../assets/patterns/705.png"), name: "Esquisto"},
	{key: 706, uri:require("../assets/patterns/706.png"), name: "Esquisto contorsionado"},
	{key: 707, uri:require("../assets/patterns/707.png"), name: "Esquisto y gneis"},
	{key: 708, uri:require("../assets/patterns/708.png"), name: "Gneis"},
	{key: 709, uri:require("../assets/patterns/709.png"), name: "Gneis contorsionado"},
	{key: 710, uri:require("../assets/patterns/710.png"), name: "Talco o esteatita"},
	{key: 711, uri:require("../assets/patterns/711.png"), name: "Roca tobacea"},
	{key: 712, uri:require("../assets/patterns/712.png"), name: "Toba de cristal"},
	{key: 713, uri:require("../assets/patterns/713.png"), name: "Toba devitrificada"},
	{key: 714, uri:require("../assets/patterns/714.png"), name: "Brecha volcánica y toba"},
	{key: 715, uri:require("../assets/patterns/715.png"), name: "Breacha volcánica o aglomerado"},
	{key: 716, uri:require("../assets/patterns/716.png"), name: "Roca zeolítica"},
	{key: 717, uri:require("../assets/patterns/717.png"), name: "Flujos basálticos"},
	{key: 718, uri:require("../assets/patterns/718.png"), name: "Granito 1"},
	//{key: 719, uri:require("../assets/patterns/719.png"), name: "Granito 2"},
	{key: 720, uri:require("../assets/patterns/720.png"), name: "Roca ígnea en bandas"},
	//{key: 721, uri:require("../assets/patterns/721.png"), name: "Roca ígnea 1"},
	{key: 722, uri:require("../assets/patterns/722.png"), name: "Roca ígnea 2"},
	//{key: 723, uri:require("../assets/patterns/723.png"), name: "Roca ígnea 3"},
	//{key: 724, uri:require("../assets/patterns/724.png"), name: "Roca ígnea 4"},
	//{key: 725, uri:require("../assets/patterns/725.png"), name: "Roca ígnea 5"},
	//{key: 726, uri:require("../assets/patterns/726.png"), name: "Roca ígnea 6"},
	//{key: 727, uri:require("../assets/patterns/727.png"), name: "Roca ígnea 7"},
	//{key: 728, uri:require("../assets/patterns/728.png"), name: "Roca ígnea 8"},
	{key: 729, uri:require("../assets/patterns/729.png"), name: "Roca porfídica 1"},
	//{key: 730, uri:require("../assets/patterns/730.png"), name: "Roca porfídica 2"},
	{key: 731, uri:require("../assets/patterns/731.png"), name: "Pantelarita"},
	{key: 732, uri:require("../assets/patterns/732.png"), name: "Cuarzo"},
	{key: 733, uri:require("../assets/patterns/733.png"), name: "Mineral"},
]